// MV-96: a derived page saying what this ecosystem's declarations oblige.
//
// The first design of this feature was killed in review for citing invariant
// identifiers in generated output. Ids are allocated from each brain's own
// table and `init` writes a table with zero rows, so a generated `MV-56` names
// a different rule — or none — in every ecosystem except the one it was
// written in. The identifier test below is the one that matters most.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { makeScratchEcosystem } from '../helpers/fixture.js';
import { loadConfig, FLOW_PATH } from '../../src/lib/config.js';
import { renderFlow } from '../../src/doors/flow.js';
import { doorsCommand } from '../../src/commands/doors.js';

const quiet = async (fn: () => Promise<number>): Promise<number> => {
  const origLog = console.log;
  const origErr = console.error;
  console.log = () => {};
  console.error = () => {};
  try {
    return await fn();
  } finally {
    console.log = origLog;
    console.error = origErr;
  }
};

async function eco(lines: string[]) {
  const tmp = mkdtempSync(join(tmpdir(), 'mvac-flow-'));
  const e = makeScratchEcosystem(tmp);
  writeFileSync(join(e.brain, '.multivac/config.yml'), [...lines, ''].join('\n'));
  return { ...e, cfg: await loadConfig(e.brain) };
}

const DECLARED = [
  'doors: [agents]',
  'sdd: speckit',
  'grapher: graphify',
  'repos:',
  '  api: ../acme-api',
];

// --- US1: the three groups ---

test('the page sorts declared obligations into automatic, gate and yours', async () => {
  const { cfg } = await eco(DECLARED);
  const page = renderFlow(cfg);
  for (const h of [
    '## Automatic — multivac does it, you do not ask',
    '## Gate — multivac refuses without it',
    '## Yours — nobody can check these',
  ]) {
    assert.ok(page.includes(h), `missing heading: ${h}`);
  }
  // The grapher's work is automatic; its artifact is a gate.
  assert.match(page, /the code graph is built where a declared repo has no `graphify-out\/graph\.json`/);
  assert.match(page, /`change close` refuses while a declared, present repo has no `graphify-out\/graph\.json`/);
});

test('a gating row leads with the command that refuses and names the artifact', async () => {
  const { cfg } = await eco(DECLARED);
  const page = renderFlow(cfg);
  assert.match(page, /- `change plan` refuses without `specs\/\*-<slug>\/spec\.md`/);
  assert.match(page, /- `change apply` refuses without `specs\/\*-<slug>\/plan\.md`/);
  assert.match(page, /- `change apply` refuses without `specs\/\*-<slug>\/tasks\.md`/);
});

test("an unprovable step carries the adapter's own reason, verbatim", async () => {
  const { cfg } = await eco(DECLARED);
  const page = renderFlow(cfg);
  // Copied from the registry entry, not re-worded here: a paraphrase would age
  // beside its source.
  assert.match(page, /STRICTLY READ-ONLY by its own spec/);
  assert.match(page, /the agent grading its own homework/);
  assert.match(page, /invisible to the filesystem/);
});

test('a brain with nothing declared still gets a useful page', async () => {
  const { cfg } = await eco(['doors: [agents]', 'repos:', '  api: ../acme-api']);
  const page = renderFlow(cfg);
  assert.match(page, /## Gate — multivac refuses without it/);
  assert.match(page, /`change close` refuses while a declared claim does not resolve/);
  assert.match(page, /no SDD tool is declared/);
  assert.match(page, /no grapher is declared/);
});

test('an unverified adapter is named as declared-but-unknown, never guessed', async () => {
  const { cfg } = await eco([
    'doors: [agents]', 'sdd: acme-not-real', 'grapher: acme-graph', 'repos:', '  api: ../acme-api',
  ]);
  const page = renderFlow(cfg);
  assert.match(page, /`acme-not-real` is declared as the SDD tool but is unknown to multivac/);
  assert.match(page, /`acme-graph` is declared as the grapher but/);
  // Nothing invented for either.
  assert.equal(page.includes('refuses without `specs/'), false);
});

// --- US2: derived, and saying so ---

test('the page carries no invariant identifier', async () => {
  // The failure the first design would have shipped. Ids are per-brain; a
  // generated one is wrong everywhere but here.
  for (const lines of [DECLARED, ['doors: [agents]', 'repos:', '  api: ../acme-api']]) {
    const { cfg } = await eco(lines);
    assert.equal(/\bMV-\d+\b/.test(renderFlow(cfg)), false, 'an identifier reached the page');
  }
});

test('it says it is generated, what regenerates it, and that it binds nothing', async () => {
  const { cfg } = await eco(DECLARED);
  const page = renderFlow(cfg);
  assert.match(page, /Generated by `multivac doors`/);
  assert.match(page, /\*\*This page binds nothing\*\*/);
  assert.match(page, /the law in `\.multivac\/invariants\.md` binds/);
});

test('changing a declaration changes the page, with no hand editing', async () => {
  const a = await eco(DECLARED);
  const b = await eco(['doors: [agents]', 'repos:', '  api: ../acme-api']);
  assert.notEqual(renderFlow(a.cfg), renderFlow(b.cfg));
});

test('writing outside the managed block survives regeneration', async () => {
  const { brain } = await eco(DECLARED);
  const ctx = { cwd: brain };
  await quiet(() => doorsCommand.run([], ctx));
  const file = join(brain, FLOW_PATH);
  writeFileSync(file, `${readFileSync(file, 'utf8')}\n\n## Ours\n\nHand-written, and it stays.\n`);
  await quiet(() => doorsCommand.run([], ctx));
  const after = readFileSync(file, 'utf8');
  assert.match(after, /## Ours\n\nHand-written, and it stays\./);
  assert.match(after, /## Gate — multivac refuses without it/);
});
