// `.multivac/flow.md` — what this ecosystem's declarations oblige, sorted.
//
// MV-96. A newly initialised brain has no single place answering "what did I
// just sign up for". The law is ninety rows, the ritual starts empty, and the
// obligations are spread across an adapter registry the operator never reads
// and command output that scrolls past — so the reasonable conclusion from
// reading a fresh repo is that nothing is enforced. That is false, and it is
// the tool's fault.
//
// Every row is RENDERED from the registry and the config — the same data the
// gates read — so it cannot describe behaviour the tool does not have. A row
// typed ABOUT a gate can drift; a row rendered FROM it cannot. Where an adapter
// states why a step is unprovable, that text is carried verbatim: a paraphrase
// would age beside its source, which is the failure this whole project exists
// to prevent.
//
// It cites COMMANDS and ARTIFACTS and never an invariant identifier. Ids are
// allocated from each brain's own table and `init` writes a table with zero
// rows, so an id generated here names a different rule — or none — in every
// ecosystem except the one it was written in. An `absent` leg keeps it that
// way, because the temptation to add one for authority is exactly what a later
// reader will feel. That leg cannot tell rendered text from a comment, so no
// concrete id is written in this file at all, not even as an example.

import type { Config } from '../types.js';
import { sddSpec } from '../adapters/registry.js';
import { proofOf } from '../adapters/sdd.js';
import { adaptersByRoot } from '../adapters/detect.js';
import { stateLabel } from '../lib/init-state.js';
import { LAW_PATH, RITUAL_PATH } from '../lib/config.js';

const HEADER = [
  '# Flow — what this ecosystem\'s declarations oblige',
  '',
  'Generated by `multivac doors` from `.multivac/config.yml` and the adapter',
  'registry. Edits inside the markers are overwritten; anything you write outside',
  `them survives. **This page binds nothing** — the law in \`${LAW_PATH}\` binds, and`,
  'this describes what it and the declared adapters already do.',
];

/** Render the flow page body (no markers). */
export function renderFlow(config: Config): string {
  const auto: string[] = [];
  const gate: string[] = [];
  const yours: string[] = [];

  // The lifecycle's own obligations: true with nothing declared, which is
  // exactly when this page is most needed.
  gate.push('- `change plan` refuses while a declared repo is missing from `landing_order`');
  // MV-150: close checks what each claim cites as well as whether it resolves.
  gate.push('- `change close` refuses while a declared claim does not resolve, or cites no stated row this change adds, touches or retires');
  gate.push('- `verify` refuses a commit whose anchors are broken — it runs in the pre-commit hook');
  auto.push('- the doors and the git hooks are re-projected by `multivac doors`');
  yours.push(`- the ritual in \`${RITUAL_PATH}\`, printed by \`change close\` and checked by nothing`);

  // MV-146: the SDD resolves in the brain alone, so its rows name no roots —
  // every one is the brain's — and under `sdd_auto: false` no row says the
  // lifecycle refuses or runs the init: it does neither then, and a row saying
  // it does is the lie this page exists to prevent. Those rows move to what is
  // yours.
  const sdds = adaptersByRoot(config, 'sdd');
  const off = ' — not gated (`sdd_auto: false`)';
  for (const [name] of sdds) {
    const spec = sddSpec(name);
    if (!spec) {
      yours.push(
        `- \`${name}\` is declared as the SDD tool but is unknown to multivac — nothing of its flow is run or gated`,
      );
      continue;
    }
    // Under `sdd_auto: false` no command runs the init either: the row is
    // the operator's, like the steps below.
    if (spec.scaffold && config.sddAuto) {
      auto.push(
        `- the \`${name}\` init is run in the brain when its \`${stateLabel(spec)}\` is missing, or the lifecycle says why it could not`,
      );
    } else if (spec.scaffold) {
      yours.push(`- the \`${name}\` init, in the brain when its \`${stateLabel(spec)}\` is missing — not run (\`sdd_auto: false\`)`);
    }
    for (const s of spec.steps ?? []) {
      // The COMMAND leads: a reader scanning this column is asking "what will
      // stop me", not "which file". Both halves come from the step itself —
      // the same two fields the gate reads — so neither can drift from it.
      if (s.artifact && s.gate) {
        if (config.sddAuto) gate.push(`- \`change ${s.gate}\` refuses without \`${s.artifact}\``);
        else yours.push(`- \`${s.artifact}\` before \`change ${s.gate}\`${off}`);
        continue;
      }
      // Ungateable: the adapter's own reason, carried whole. A paraphrase
      // would age beside its source.
      // MV-147: the verb is the first backticked command of a required binary —
      // opsx's apply run names `change apply` before `openspec instructions
      // apply …` — then a chat command's `/…` token, then the point.
      const verb =
        [...s.run.matchAll(/`([^`]+)`/g)].map((m) => m[1]).find((c) => spec.required.includes(c.split(' ')[0])) ??
        /\/[\w.:-]+/.exec(s.run)?.[0] ??
        s.at;
      yours.push(`- \`${verb}\` — ${proofOf(s).slice('ungateable: '.length)}`);
    }
    // MV-135: the project document, from the same step the gate reads.
    for (const p of spec.projectSteps ?? []) {
      if (p.reportOnly) {
        yours.push(`- \`${p.artifact}\` \`${p.reportOnly.key}:\` — ${p.run}; optional, reported and never gated`);
      } else if (config.sddAuto) {
        gate.push(`- \`change plan\` refuses while \`${p.artifact}\` is missing, empty or still the template, in the brain`);
      } else {
        yours.push(`- \`${p.artifact}\` in the brain, before \`change plan\`${off}`);
      }
    }
  }
  if (sdds.size === 0) {
    yours.push('- no SDD tool is declared, so no specification flow is printed or gated');
  }

  return [
    ...HEADER,
    '',
    '## Automatic — multivac does it, you do not ask',
    '',
    ...auto,
    '',
    '## Gate — multivac refuses without it',
    '',
    ...gate,
    '',
    '## Yours — nobody can check these',
    '',
    ...yours,
  ].join('\n');
}
