// `.multivac/flow.md` — what this ecosystem's declarations oblige, sorted.
//
// MV-96. A newly initialised brain has no single place answering "what did I
// just sign up for". The law is ninety rows, the ritual starts empty, and the
// obligations are spread across an adapter registry the operator never reads
// and command output that scrolls past — so the reasonable conclusion from
// reading a fresh repo is that nothing is enforced. That is false, and it is
// the tool's fault.
//
// Every row is RENDERED from the registry and the config — the same data the
// gates read — so it cannot describe behaviour the tool does not have. A row
// typed ABOUT a gate can drift; a row rendered FROM it cannot. Where an adapter
// states why a step is unprovable, that text is carried verbatim: a paraphrase
// would age beside its source, which is the failure this whole project exists
// to prevent.
//
// It cites COMMANDS and ARTIFACTS and never an invariant identifier. Ids are
// allocated from each brain's own table and `init` writes a table with zero
// rows, so an id generated here names a different rule — or none — in every
// ecosystem except the one it was written in. An `absent` leg keeps it that
// way, because the temptation to add one for authority is exactly what a later
// reader will feel. That leg cannot tell rendered text from a comment, so no
// concrete id is written in this file at all, not even as an example.

import type { Config } from '../types.js';
import { grapherSpec, sddSpec, unverifiedGrapher } from '../adapters/registry.js';
import { proofOf } from '../adapters/sdd.js';
import { adaptersByRoot, askedGraphers, brainHoldsCode, hookRefreshes } from '../adapters/detect.js';
import { stateLabel } from '../lib/init-state.js';
import { LAW_PATH, RITUAL_PATH } from '../lib/config.js';

const HEADER = [
  '# Flow — what this ecosystem\'s declarations oblige',
  '',
  'Generated by `multivac doors` from `.multivac/config.yml` and the adapter',
  'registry. Edits inside the markers are overwritten; anything you write outside',
  `them survives. **This page binds nothing** — the law in \`${LAW_PATH}\` binds, and`,
  'this describes what it and the declared adapters already do.',
];

/** Render the flow page body (no markers). */
export function renderFlow(config: Config): string {
  const auto: string[] = [];
  const gate: string[] = [];
  const yours: string[] = [];

  // The lifecycle's own obligations: true with nothing declared, which is
  // exactly when this page is most needed.
  gate.push('- `change plan` refuses while a declared repo is missing from `landing_order`');
  gate.push('- `change close` refuses while a declared claim does not resolve');
  gate.push('- `verify` refuses a commit whose anchors are broken — it runs in the pre-commit hook');
  auto.push('- the doors and the git hooks are re-projected by `multivac doors`');
  yours.push(`- the ritual in \`${RITUAL_PATH}\`, printed by \`change close\` and checked by nothing`);

  // MV-122: a row per adapter a declared root resolves, not the ecosystem's
  // alone. A grapher row names its roots only when some declared root resolves
  // otherwise, so a config naming only top-level adapters renders what it did.
  // MV-148: the brain is one of those roots only where it holds code — one
  // that holds none resolves no grapher, and counting it named every grapher's
  // repos as though the brain were left out of it.
  const holds = brainHoldsCode(config);
  const declared = (holds ? 1 : 0) + Object.values(config.repos).filter((r) => !r.isBrain).length;
  const every = (roots: string[]): boolean => roots.length === declared;
  const inRoots = (roots: string[]): string => (every(roots) ? '' : ` — in ${roots.join(', ')}`);
  const forRoots = (roots: string[]): string => (every(roots) ? '' : ` for ${roots.join(', ')}`);

  // MV-146: the SDD resolves in the brain alone, so its rows name no roots —
  // every one is the brain's — and under `sdd_auto: false` no row says the
  // lifecycle refuses or runs the init: it does neither then, and a row saying
  // it does is the lie this page exists to prevent. Those rows move to what is
  // yours.
  const sdds = adaptersByRoot(config, 'sdd');
  const off = ' — not gated (`sdd_auto: false`)';
  for (const [name] of sdds) {
    const spec = sddSpec(name);
    if (!spec) {
      yours.push(
        `- \`${name}\` is declared as the SDD tool but is unknown to multivac — nothing of its flow is run or gated`,
      );
      continue;
    }
    // Under `sdd_auto: false` no command runs the init either: the row is
    // the operator's, like the steps below.
    if (spec.scaffold && config.sddAuto) {
      auto.push(
        `- the \`${name}\` init is run in the brain when its \`${stateLabel(spec)}\` is missing, or the lifecycle says why it could not`,
      );
    } else if (spec.scaffold) {
      yours.push(`- the \`${name}\` init, in the brain when its \`${stateLabel(spec)}\` is missing — not run (\`sdd_auto: false\`)`);
    }
    for (const s of spec.steps ?? []) {
      // The COMMAND leads: a reader scanning this column is asking "what will
      // stop me", not "which file". Both halves come from the step itself —
      // the same two fields the gate reads — so neither can drift from it.
      if (s.artifact && s.gate) {
        if (config.sddAuto) gate.push(`- \`change ${s.gate}\` refuses without \`${s.artifact}\``);
        else yours.push(`- \`${s.artifact}\` before \`change ${s.gate}\`${off}`);
        continue;
      }
      // Ungateable: the adapter's own reason, carried whole. A paraphrase
      // would age beside its source.
      // MV-147: the verb is the first backticked command of a required binary —
      // opsx's apply run names `change apply` before `openspec instructions
      // apply …` — then a chat command's `/…` token, then the point.
      const verb =
        [...s.run.matchAll(/`([^`]+)`/g)].map((m) => m[1]).find((c) => spec.required.includes(c.split(' ')[0])) ??
        /\/[\w.:-]+/.exec(s.run)?.[0] ??
        s.at;
      yours.push(`- \`${verb}\` — ${proofOf(s).slice('ungateable: '.length)}`);
    }
    // MV-135: the project document, from the same step the gate reads.
    for (const p of spec.projectSteps ?? []) {
      if (p.reportOnly) {
        yours.push(`- \`${p.artifact}\` \`${p.reportOnly.key}:\` — ${p.run}; optional, reported and never gated`);
      } else if (config.sddAuto) {
        gate.push(`- \`change plan\` refuses while \`${p.artifact}\` is missing, empty or still the template, in the brain`);
      } else {
        yours.push(`- \`${p.artifact}\` in the brain, before \`change plan\`${off}`);
      }
    }
  }
  if (sdds.size === 0) {
    yours.push('- no SDD tool is declared, so no specification flow is printed or gated');
  }

  const graphers = adaptersByRoot(config, 'grapher');
  // MV-148: a declared grapher no writable code repo resolves is not "no
  // grapher declared": the brain holds no code, so it is built nowhere yet,
  // and a repo marked `managed: false` is never built or gated (MV-125) —
  // `askedGraphers` leaves those repos out.
  const asked = askedGraphers(config);
  const noWritable = (name: string): string =>
    `- \`${name}\` is declared, and no writable code repo resolves it yet: the brain holds no code, so none here; each code repo that resolves it gets its own when \`repos sync\` or a change reaches it`;
  let verified = false;
  for (const [name, roots] of graphers) {
    const spec = grapherSpec(name, config.graphers);
    if (!spec) {
      auto.push(`- \`${name}\` is declared as the grapher${forRoots(roots)} but ${unverifiedGrapher(name)}`);
      continue;
    }
    if (!holds && !asked.get(name)?.length) {
      auto.push(noWritable(name));
      continue;
    }
    verified = true;
    // MV-140: what MV-134 does, not what came before it.
    // MV-148: "after each edit" only of a grapher a hook of the brain is declared
    // to run — the door's answer, asked through the one question (MV-149's
    // `hookRefreshes`). The page said it of every grapher wherever a door had
    // a post-edit hook, and promised a refresh nothing ran. Declared, like the
    // door (MV-93): whether this machine wired it is `doors`' and `doctor`'s.
    const hooked = hookRefreshes(config, name);
    // MV-149: a local index is also built in each change worktree at `change
    // apply`, and land syncs it there and commits none — the page said land
    // committed it, which it never did.
    const local = spec.artifactKind === 'local';
    auto.push(
      `- the code graph is built where \`multivac repos sync\` or a change reaches a repo with no \`${spec.artifacts[0]}\`${local ? ', and in each change worktree at `change apply`' : ''}, refreshed ${hooked ? 'after each edit through the harness hook, and ' : ''}at \`change land\`, where it is ${local ? 'synced and never committed' : 'committed on the change branch'}, and at \`change close\`, in ${every(roots) ? 'every declared repo' : roots.join(', ')}`,
    );
    if (config.grapherAuto) {
      // MV-148: the brain is gated only where it holds code.
      const who = holds ? 'the brain or a repo the change names' : 'a repo the change names';
      gate.push(`- \`change close\` refuses while ${who} has no \`${spec.artifacts[0]}\`${inRoots(roots)}`);
    }
    if (spec.queries && spec.queries.length > 0) {
      yours.push(
        `- asking \`${name}\` before reading the tree — no committed file records a query${name === 'graphify' ? ': graphify writes only an untracked `graphify-out/cache/last_query_stamp`, a query that found nothing writes it too, and its own Claude hook nudges toward a query without blocking a read' : ''}${inRoots(roots)}`,
      );
    }
  }
  if (graphers.size === 0) {
    // MV-148: the ecosystem's declaration, where no code repo resolves it —
    // unverified, it is named as such (MV-59): nothing builds it anywhere.
    const [top] = holds ? [] : asked.keys();
    auto.push(
      top === undefined
        ? '- no grapher is declared, so no graph is built or required'
        : grapherSpec(top, config.graphers) === null
          ? `- \`${top}\` is declared as the grapher but ${unverifiedGrapher(top)}`
          : noWritable(top),
    );
  }
  if (verified && !config.grapherAuto) {
    yours.push('- `grapher_auto: false` — the graph is still built, and `change close` no longer requires it');
  }

  return [
    ...HEADER,
    '',
    '## Automatic — multivac does it, you do not ask',
    '',
    ...auto,
    '',
    '## Gate — multivac refuses without it',
    '',
    ...gate,
    '',
    '## Yours — nobody can check these',
    '',
    ...yours,
  ].join('\n');
}
