// `.multivac/flow.md` — what this ecosystem's declarations oblige, sorted.
//
// MV-96. A newly initialised brain has no single place answering "what did I
// just sign up for". The law is ninety rows, the ritual starts empty, and the
// obligations are spread across an adapter registry the operator never reads
// and command output that scrolls past — so the reasonable conclusion from
// reading a fresh repo is that nothing is enforced. That is false, and it is
// the tool's fault.
//
// Every row is RENDERED from the registry and the config — the same data the
// gates read — so it cannot describe behaviour the tool does not have. A row
// typed ABOUT a gate can drift; a row rendered FROM it cannot. Where an adapter
// states why a step is unprovable, that text is carried verbatim: a paraphrase
// would age beside its source, which is the failure this whole project exists
// to prevent.
//
// It cites COMMANDS and ARTIFACTS and never an invariant identifier. Ids are
// allocated from each brain's own table and `init` writes a table with zero
// rows, so an id generated here names a different rule — or none — in every
// ecosystem except the one it was written in. An `absent` leg keeps it that
// way, because the temptation to add one for authority is exactly what a later
// reader will feel. That leg cannot tell rendered text from a comment, so no
// concrete id is written in this file at all, not even as an example.

import type { Config } from '../types.js';
import { doorTargets, grapherSpec, sddSpec, unverifiedGrapher } from '../adapters/registry.js';
import { proofOf } from '../adapters/sdd.js';
import { adaptersByRoot } from '../adapters/detect.js';
import { stateLabel } from '../lib/init-state.js';
import { LAW_PATH, RITUAL_PATH } from '../lib/config.js';

const HEADER = [
  '# Flow — what this ecosystem\'s declarations oblige',
  '',
  'Generated by `multivac doors` from `.multivac/config.yml` and the adapter',
  'registry. Edits inside the markers are overwritten; anything you write outside',
  `them survives. **This page binds nothing** — the law in \`${LAW_PATH}\` binds, and`,
  'this describes what it and the declared adapters already do.',
];

/** Render the flow page body (no markers). */
export function renderFlow(config: Config): string {
  const auto: string[] = [];
  const gate: string[] = [];
  const yours: string[] = [];

  // The lifecycle's own obligations: true with nothing declared, which is
  // exactly when this page is most needed.
  gate.push('- `change plan` refuses while a declared repo is missing from `landing_order`');
  gate.push('- `change close` refuses while a declared claim does not resolve');
  gate.push('- `verify` refuses a commit whose anchors are broken — it runs in the pre-commit hook');
  auto.push('- the doors and the git hooks are re-projected by `multivac doors`');
  yours.push(`- the ritual in \`${RITUAL_PATH}\`, printed by \`change close\` and checked by nothing`);

  // MV-122: a row per adapter a declared root resolves, not the ecosystem's
  // alone. A row names its roots only when some declared root resolves
  // otherwise, so a config naming only top-level adapters renders what it did.
  const declared = 1 + Object.values(config.repos).filter((r) => !r.isBrain).length;
  const every = (roots: string[]): boolean => roots.length === declared;
  const inRoots = (roots: string[]): string => (every(roots) ? '' : ` — in ${roots.join(', ')}`);
  const forRoots = (roots: string[]): string => (every(roots) ? '' : ` for ${roots.join(', ')}`);

  const sdds = adaptersByRoot(config, 'sdd');
  for (const [name, roots] of sdds) {
    const spec = sddSpec(name);
    if (!spec) {
      yours.push(
        `- \`${name}\` is declared as the SDD tool${forRoots(roots)} but is unknown to multivac — nothing of its flow is run or gated`,
      );
      continue;
    }
    if (spec.scaffold) {
      auto.push(
        `- the \`${name}\` init is run in a declared repo whose \`${stateLabel(spec)}\` is missing, or the lifecycle says why it could not${inRoots(roots)}`,
      );
    }
    for (const s of spec.steps ?? []) {
      // The COMMAND leads: a reader scanning this column is asking "what will
      // stop me", not "which file". Both halves come from the step itself —
      // the same two fields the gate reads — so neither can drift from it.
      if (s.artifact && s.gate) {
        gate.push(`- \`change ${s.gate}\` refuses without \`${s.artifact}\`${inRoots(roots)}`);
        continue;
      }
      // Ungateable: the adapter's own reason, carried whole. A paraphrase
      // would age beside its source.
      const verb = /\/[\w.:-]+/.exec(s.run)?.[0] ?? s.at;
      yours.push(`- \`${verb}\` — ${proofOf(s).slice('ungateable: '.length)}${inRoots(roots)}`);
    }
    // MV-135: the project document, from the same step the gate reads.
    for (const p of spec.projectSteps ?? []) {
      if (p.reportOnly) {
        yours.push(`- \`${p.artifact}\` \`${p.reportOnly.key}:\` — ${p.run}; optional, reported and never gated${inRoots(roots)}`);
      } else {
        gate.push(`- \`change plan\` refuses while \`${p.artifact}\` is missing, empty or still the template, in every repo where \`${name}\` is installed${inRoots(roots)}`);
      }
    }
  }
  if (sdds.size === 0) {
    yours.push('- no SDD tool is declared, so no specification flow is printed or gated');
  }

  const graphers = adaptersByRoot(config, 'grapher');
  let verified = false;
  for (const [name, roots] of graphers) {
    const spec = grapherSpec(name, config.graphers);
    if (!spec) {
      auto.push(`- \`${name}\` is declared as the grapher${forRoots(roots)} but ${unverifiedGrapher(name)}`);
      continue;
    }
    verified = true;
    // MV-140: what MV-134 does, not what came before it.
    auto.push(
      `- the code graph is built where \`multivac repos sync\` or a change reaches a repo with no \`${spec.artifacts[0]}\`, refreshed ${config.doors.some((d) => doorTargets[d]?.hookConfig?.postEdit) ? 'after each edit through the harness hook, and ' : ''}at \`change land\`, where it is committed on the change branch, and at \`change close\`, in ${every(roots) ? 'every declared repo' : roots.join(', ')}`,
    );
    if (config.grapherAuto) {
      gate.push(
        `- \`change close\` refuses while the brain or a repo the change names has no \`${spec.artifacts[0]}\`${inRoots(roots)}`,
      );
    }
    if (spec.queries && spec.queries.length > 0) {
      yours.push(
        `- asking \`${name}\` before reading the tree — no committed file records a query${name === 'graphify' ? ': graphify writes only an untracked `graphify-out/cache/last_query_stamp`, a query that found nothing writes it too, and its own Claude hook nudges toward a query without blocking a read' : ''}${inRoots(roots)}`,
      );
    }
  }
  if (graphers.size === 0) {
    auto.push('- no grapher is declared, so no graph is built or required');
  }
  if (verified && !config.grapherAuto) {
    yours.push('- `grapher_auto: false` — the graph is still built, and `change close` no longer requires it');
  }

  return [
    ...HEADER,
    '',
    '## Automatic — multivac does it, you do not ask',
    '',
    ...auto,
    '',
    '## Gate — multivac refuses without it',
    '',
    ...gate,
    '',
    '## Yours — nobody can check these',
    '',
    ...yours,
  ].join('\n');
}
