// multivac seed — the DETERMINISTIC half: inventory each declared+present
// repo's boundaries into .multivac/seed-report.md. No LLM, no interpretation;
// the agent reads the report and drafts proposed claims (see the skill).

import { writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { Command, CommandContext } from '../types.js';
import { loadConfig } from '../lib/config.js';
import { lsFiles } from '../lib/git.js';
import { say } from '../lib/out.js';
import { classify } from '../seed/inventory.js';

export const REPORT_PATH = '.multivac/seed-report.md';

async function runSeed(argv: string[], ctx: CommandContext): Promise<number> {
  const dirArg = argv.find((a) => !a.startsWith('-'));
  const brainDir = resolve(ctx.cwd, dirArg ?? '.');
  const cfg = await loadConfig(brainDir); // throws actionable ConfigError

  const lines: string[] = [
    '# seed report',
    '',
    'Deterministic boundary inventory, generated by `multivac seed`.',
    'Nothing here is law: the agent drafts `proposed` rows from it; a human enacts.',
  ];
  const skipped: string[] = [];
  let present = 0;

  const keys = Object.keys(cfg.repos);
  if (keys.length === 0) {
    lines.push('', 'No repos declared — add them under `repos:` in `.multivac/config.yml`.');
  }
  for (const key of keys) {
    const entry = cfg.repos[key];
    const repoDir = resolve(brainDir, entry.path);
    let files: string[];
    try {
      files = await lsFiles(repoDir); // never clone on implicit paths
    } catch {
      skipped.push(`- ${key} (${entry.path}) — not present; run \`multivac repos sync\` to clone`);
      continue;
    }
    present++;
    lines.push('', `## ${key} (${entry.path})`);
    const buckets = classify(files);
    if (buckets.size === 0) {
      lines.push('', 'No boundary files found.');
      continue;
    }
    for (const [category, list] of buckets) {
      lines.push('', `### ${category} (${list.length})`, '');
      for (const f of list) lines.push(`- ${f}`);
    }
  }

  if (skipped.length > 0) lines.push('', '## skipped', '', ...skipped);
  lines.push(
    '',
    '## next',
    '',
    'The agent reads these files and drafts proposed claims — see the multivac skill.',
  );

  await writeFile(join(brainDir, REPORT_PATH), lines.join('\n') + '\n');
  say(
    `seed: wrote ${REPORT_PATH} — ${present} repo(s) inventoried` +
      (skipped.length > 0 ? `, ${skipped.length} skipped` : ''),
  );
  say('seed: next — read the report and draft proposed claims (see the multivac skill)');
  return 0;
}

export const seed: Command = {
  name: 'seed',
  help: `deterministic boundary inventory -> ${REPORT_PATH}`,
  run: runSeed,
};
