// multivac seed — the DETERMINISTIC half: inventory each declared+present
// repo's boundaries into .multivac/seed-report.md. No LLM, no interpretation;
// the agent reads the report, takes the open questions to a human, and drafts
// proposed claims (see the skill). Flow: seed → questions → interview → law.

import { writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { Command, CommandContext } from '../types.js';
import { surfaceFrom, undeclared } from '../lib/args.js';
import { parseArgs, type ArgsDef } from 'citty';
import { loadConfig } from '../lib/config.js';
import { lsFiles } from '../lib/git.js';
import { say, warn } from '../lib/out.js';
import { classify } from '../seed/inventory.js';

export const REPORT_PATH = '.multivac/seed-report.md';

/** Per-category listing cap: 96% of saleor's report was migration filenames. */
const CAP = 25;

/** How many found files an open question names before trailing off. */
const NAME_CAP = 10;

const nameSome = (files: string[]): string =>
  files.slice(0, NAME_CAP).join(', ') + (files.length > NAME_CAP ? ', …' : '');

/** Which deploy stacks the inventory saw — each one is a candidate authority. */
function deployStacks(deploy: string[], terraform: string[], docker: string[]): string[] {
  const stacks: [string, boolean][] = [
    ['helm', deploy.some((f) => f.includes('Chart.yaml') || f.includes('helm'))],
    ['kustomize', deploy.some((f) => f.includes('kustomization.yaml'))],
    ['skaffold', deploy.some((f) => f.includes('skaffold.yaml'))],
    ['raw manifests', deploy.some((f) => /(^|\/)(kubernetes-manifests|k8s|deployment)\//.test(f))],
    ['terraform', terraform.length > 0],
    ['compose', docker.some((f) => f.includes('compose'))],
  ];
  return stacks.filter(([, hit]) => hit).map(([name]) => name);
}

/**
 * The three questions every cold adopter of a foreign ecosystem hit
 * (measurement 2 §2), instantiated against what seed found. Seed cannot
 * answer them; guessed answers become wrong law. They are the interview's
 * input.
 */
function openQuestions(gates: string[], prose: string[], stacks: string[]): string[] {
  const lines = [
    '',
    '## open questions — the interview needs these answered',
    '',
    'Seed names files; it cannot answer what they mean. Every rule drafted',
    'without these answers is a guess, and a wrong guess becomes wrong law.',
    'Put them to a maintainer (interview protocol: the multivac skill,',
    '`references/interview.md`) before enacting anything:',
    '',
    '1. **Debt or intent?** Where the code violates a rule written below,',
    '   is the violation debt to be fixed or a sign the written rule is dead?',
    '   Grep HEAD for each candidate rule before filing it.' +
      (gates.length > 0 ? ` Rules in machine form found here: ${nameSome(gates)}.` : ''),
    '2. **Law or taste?** Which written rules are enforced law (violations',
    '   get blocked) and which are taste? Only a maintainer can say.' +
      (prose.length > 0
        ? ` Prose that already states rules — prior art, read it first: ${nameSome(prose)}.`
        : ''),
    '3. **Which authority wins?** When two sources disagree, the law table',
    '   must name the winner before the disagreement is found the hard way.' +
      (stacks.length > 1 ? ` This ecosystem deploys via ${stacks.join(', ')} in parallel.` : '') +
      (gates.length > 0 && prose.length > 0 ? ' Machine gates and prose docs both exist here.' : ''),
  ];
  return lines;
}

/** What seed takes. One declaration: citty parses it, `undeclared` refuses against it. */
const ARGS = {
  dir: { type: 'positional', required: false, description: 'the brain; defaults to the working directory' },
} satisfies ArgsDef;

async function runSeed(argv: string[], ctx: CommandContext): Promise<number> {
  // MV-85: before the inventory and before the report is written. seed took the
  // first non-flag and ignored every flag, so a typo changed nothing and said so
  // to nobody.
  const bad = undeclared('seed', argv, surfaceFrom(ARGS));
  if (bad) {
    warn(bad);
    return 2;
  }
  const brainDir = resolve(ctx.cwd, parseArgs(argv, ARGS).dir ?? '.');
  const cfg = await loadConfig(brainDir); // throws actionable ConfigError — exit 2, cli.ts

  const lines: string[] = [
    '# seed report',
    '',
    'Deterministic boundary inventory, generated by `multivac seed`.',
    'Nothing here is law: the agent drafts `proposed` rows from it; a human enacts.',
  ];
  const skipped: string[] = [];
  let present = 0;
  const gates: string[] = [];
  const prose: string[] = [];
  const deploy: string[] = [];
  const terraform: string[] = [];
  const docker: string[] = [];

  const keys = Object.keys(cfg.repos);
  if (keys.length === 0) {
    lines.push('', 'No repos declared — add them under `repos:` in `.multivac/config.yml`.');
  }
  for (const key of keys) {
    const entry = cfg.repos[key];
    const repoDir = resolve(brainDir, entry.path);
    let files: string[];
    try {
      files = await lsFiles(repoDir); // never clone on implicit paths
    } catch {
      skipped.push(`- ${key} (${entry.path}) — not present; run \`multivac repos sync\` to clone`);
      continue;
    }
    present++;
    lines.push('', `## ${key} (${entry.path})`);
    const buckets = classify(files);
    if (buckets.size === 0) {
      lines.push('', 'No boundary files found.');
      continue;
    }
    const prefix = keys.length > 1 ? `${key}:` : '';
    gates.push(...(buckets.get('policy gates') ?? []).map((f) => prefix + f));
    prose.push(...(buckets.get('decisions / intent') ?? []).map((f) => prefix + f));
    deploy.push(...(buckets.get('deploy manifests') ?? []));
    terraform.push(...(buckets.get('terraform') ?? []));
    docker.push(...(buckets.get('docker') ?? []));
    for (const [category, list] of buckets) {
      lines.push('', `### ${category} (${list.length})`, '');
      for (const f of list.slice(0, CAP)) lines.push(`- ${f}`);
      if (list.length > CAP) lines.push(`- … and ${list.length - CAP} more`);
    }
  }

  if (skipped.length > 0) lines.push('', '## skipped', '', ...skipped);
  if (present > 0) {
    lines.push(...openQuestions(gates, prose, deployStacks(deploy, terraform, docker)));
  }
  lines.push(
    '',
    '## next',
    '',
    'seed → questions → interview → law. Read the inventory by category, take',
    'the open questions to a maintainer, then draft proposed claims — see the',
    'multivac skill (`references/discovery.md`).',
  );

  await writeFile(join(brainDir, REPORT_PATH), lines.join('\n') + '\n');
  say(
    `seed: wrote ${REPORT_PATH} — ${present} repo(s) inventoried` +
      (skipped.length > 0 ? `, ${skipped.length} skipped` : ''),
  );
  say('seed: next — take the open questions to a maintainer, then draft proposed claims (see the multivac skill)');
  return 0;
}

export const seed: Command = {
  name: 'seed',
  help: `deterministic boundary inventory -> ${REPORT_PATH}`,
  usage: [
    'usage: multivac seed [dir]',
    '  dir   the brain; defaults to the working directory',
    'No flags. Reads every declared repo and writes the inventory; it proposes',
    'nothing and decides nothing — the open questions go to a human.',
  ],
  run: runSeed,
};
